### PR TITLE
Variant of fold() that allows the closure to return a Future

### PR DESCRIPTION
**Pull request by djc**
This saves off the error and then runs through the `StateStream` until it sees `Done`, then returns the error together with the `State`. It would be nice if `StateStream` had some way to destroy it early, returning the state. Any thoughts about how that could look?

### CODE REVIEW

**Comment by sfackler** [comment]
Yeah, the semantics around these kinds of adaptors is a bit tricky, and why I got rid of them initially with the new setup. You can't in general yank the state out of the stream early. For example, I wrote this library for the stream of rows of data for tokio-postgres. There, the connection is in "row streaming mode" until all of the rows have been read regardless of what's going on on the client side. If we pulled the connection out of the rows stream, it's just going to be in a bad state.

I think potentially the best option is to require that the future have an error type of `enum Void {}` (which would eventually become `!` when that type is stabilized) so we don't have to worry about how to handle errors coming out of the future.

**Comment by djc** [comment]
I have to say that option doesn't feel very satisfying. One of my use cases is folding IMAP protocol responses until I have all of the metadata concerning a single message, which I then want to insert into a database. I think `fold` is the most sensible (only) option by far, but I really don't want to lose the option of bubbling any errors from the database future up.

So why not add another method to `StateStream`, with a default implementation of skipping over all the `StreamEvent::Next`s and yielding the `Done`? The `StateStream` implementer can provide a more efficient implementation if one is possible, and the `StateStream` trait can be much more fully-featured again. I think this also is imperative for making `StateStream` more acceptable in the longer term as a replacement for `Stream` in all these cases where some state is involved.

**Comment by sfackler** [comment]
My concern with fast forwarding past the remainder of the stream after a user-triggered error can run into an error itself. I don't want to have to throw that away.

**Comment by djc** [comment]
So for methods like `fold()` that take a closure, can we return a tuple of two `Result`s, where the first  represents a possible error from the passed-in closure while the second represents a possible error from fast-forwarding through the remaining stream?

**Comment by sfackler** [comment]
Yeah, we could do something like that but it seems like there'd be some pretty severe ergonomic issues. It might be simpler to have the fold future have an`Item = Result<T, E>` instead? There's no option to "fast forward" over the remainder of the stream in that case, but I don't know how common it is to be able to do something special there.

**Pull request closed without merging**
